"""Agent provisioning — `stevens agent provision <name> --preset <preset>`.

One command for new agents:
    1. generates an Ed25519 keypair (private key chmod 0600)
    2. registers the public key in agents.yaml
    3. merges a policy preset into capabilities.yaml under the agent's name
    4. writes ``~/.config/stevens/agents/<name>.env`` so `stevens agent run`
       can pick the agent up without manual env-var configuration

Re-running on an existing agent without ``--force`` errors out — silent
key rotation is exactly the kind of thing this architecture is meant to
prevent. ``--force`` rotates: the old pubkey is removed from agents.yaml,
the new one written, and any preset merge is re-attempted (which is a
no-op if the existing rules match).
"""

from __future__ import annotations

import base64
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import nacl.signing
import yaml

from .presets import Preset, PresetError, load_preset, merge_into_capabilities


class ProvisionError(Exception):
    """Raised on configuration errors during provisioning."""


@dataclass(frozen=True)
class ProvisionResult:
    name: str
    key_path: Path
    env_path: Path
    pubkey_b64: str
    preset_applied: Optional[str]
    preset_changed: bool


def default_agents_dir() -> Path:
    """``~/.config/stevens/agents/`` (or ``$XDG_CONFIG_HOME/stevens/agents/``)."""
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "stevens" / "agents"


def _generate_keypair() -> tuple[bytes, bytes]:
    """Return (private_key_bytes, public_key_bytes) — both 32-byte raw."""
    sk = nacl.signing.SigningKey.generate()
    return bytes(sk), bytes(sk.verify_key)


def _read_agents_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text()) or {}
    if not isinstance(loaded, dict):
        raise ProvisionError(f"top-level of {path} must be a map")
    return loaded


def _write_env_file(env_path: Path, *, name: str, key_path: Path, socket_path: str) -> None:
    env_path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        f"# stevens agent profile for {name!r}\n"
        f"# generated by `stevens agent provision`\n"
        f"STEVENS_CALLER_NAME={name}\n"
        f"STEVENS_PRIVATE_KEY_PATH={key_path}\n"
        f"STEVENS_SECURITY_SOCKET={socket_path}\n"
    )
    env_path.write_text(body)
    env_path.chmod(0o600)


def provision_agent(
    *,
    name: str,
    preset_name: Optional[str],
    agents_yaml: Path,
    capabilities_yaml: Path,
    agents_dir: Optional[Path] = None,
    socket_path: str = "/run/stevens/security.sock",
    force: bool = False,
    presets_dir: Optional[Path] = None,
) -> ProvisionResult:
    """Provision a new agent end-to-end. See module docstring."""
    if not name.replace("_", "").isalnum():
        raise ProvisionError(
            f"agent name must be snake_case alnum, got {name!r}"
        )

    agents_dir = agents_dir or default_agents_dir()
    key_path = agents_dir / f"{name}.key"
    env_path = agents_dir / f"{name}.env"

    # Check existing registration in agents.yaml.
    data = _read_agents_yaml(agents_yaml)
    agents = data.get("agents") or []
    existing_idx = next(
        (i for i, e in enumerate(agents) if isinstance(e, dict) and e.get("name") == name),
        None,
    )
    if existing_idx is not None and not force:
        raise ProvisionError(
            f"agent {name!r} already registered in {agents_yaml}; "
            f"pass --force to rotate (this regenerates the key — old key "
            f"file becomes useless)"
        )

    # Resolve preset BEFORE generating a key, so a bad preset name doesn't
    # leave a half-provisioned agent on disk.
    preset: Optional[Preset] = None
    if preset_name is not None:
        preset = load_preset(preset_name, presets_dir=presets_dir)

    # Generate keypair.
    sk_bytes, pk_bytes = _generate_keypair()
    sk_b64 = base64.b64encode(sk_bytes).decode("ascii")
    pk_b64 = base64.b64encode(pk_bytes).decode("ascii")

    # Write private key.
    agents_dir.mkdir(parents=True, exist_ok=True)
    key_path.write_text(sk_b64 + "\n")
    key_path.chmod(0o600)

    # Update agents.yaml.
    new_entry = {"name": name, "pubkey_b64": pk_b64}
    if existing_idx is not None:
        agents[existing_idx] = new_entry
    else:
        agents.append(new_entry)
    data["agents"] = agents
    agents_yaml.parent.mkdir(parents=True, exist_ok=True)
    agents_yaml.write_text(yaml.safe_dump(data, sort_keys=False))

    # Apply preset to capabilities.yaml (if requested).
    preset_changed = False
    if preset is not None:
        try:
            preset_changed = merge_into_capabilities(
                capabilities_yaml, name, preset
            )
        except PresetError as e:
            raise ProvisionError(str(e)) from e

    # Write env profile.
    _write_env_file(env_path, name=name, key_path=key_path, socket_path=socket_path)

    return ProvisionResult(
        name=name,
        key_path=key_path,
        env_path=env_path,
        pubkey_b64=pk_b64,
        preset_applied=preset_name,
        preset_changed=preset_changed,
    )
